# Generated by Django 4.1.5 on 2023-01-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='en_adopcion',
            field=models.BooleanField(default=False, verbose_name='Si/No'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='extras',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
