# Generated by Django 4.1.5 on 2023-01-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_mascota_foto_mensajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='extras',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='personalidad',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=300),
        ),
    ]
