# Generated by Django 4.1.5 on 2023-01-25 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_mascota_extras_alter_mascota_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='asunto',
            field=models.CharField(default='asunto', max_length=150),
        ),
        migrations.CreateModel(
            name='Adopciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField(max_length=200)),
                ('mascota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.mascota')),
            ],
        ),
    ]
