# Generated by Django 4.1.5 on 2023-01-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_mensajes_asunto_adopciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='en_adopcion',
            field=models.BooleanField(default=False, verbose_name='En adopción/No está en adopción'),
        ),
    ]
