# Generated by Django 4.1.5 on 2023-01-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_mascota_en_adopcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.CharField(default='no', max_length=150),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='en_adopcion',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=100),
        ),
    ]
